version: 0.2

phases:
  install:
    commands:
    - apt-get -y update && apt-get -y install awscli
  pre_build:
    commands:
    - aws --version
    - docker --version
    - echo "[info] logging in to Amazon ECR..."
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo "[info] build java"
    
